# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Yury Verush
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Creative Developer, Data Enthusiast, and Combat Veteran.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "yury.verush@gmail.com"# Full email address, e.g. 
  bitbucket:
  dribbble: "https://dribbble.com/yury_verush"
  facebook: "https://www.facebook.com/yverush"
  flickr: "www.flickr.com/photos/yvrush/"
  github: "https://github.com/yvrush"
  google_plus: "https://plus.google.com/+YuryVerush"
  instagram: "https://www.instagram.com/yvrush/"
  linkedin: "https://www.linkedin.com/in/yuryverush/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "yuryverush"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]